# Generated by Django 4.2 on 2023-05-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
